### ISSUE TITLE
虚拟机型号多少

### ISSUE THREAD

**Issue by Iamluanbujun** [Poison02/healthcare#1]
大佬，我想问问你虚拟机用的什么型号，我用我的Androidstudio显示不完全你的布局画面

**Comment by Poison02** [comment]
在平常的作业中是用的AndroidStudio自带的**Pixel 5 API 30**，之后换成了手机模拟器（我用的雷电模拟器），隐约记得使用的**Google**类型的手机，具体哪个我也忘了，因为我重装过电脑所以我也找不见了，只能你自己去看一看了哈。
